import type { AuditAction } from "@/lib/generated/prisma/enums";

export const AUDIT_ACTION_LABELS: Record<AuditAction, string> = {
  PROFILE_CREATED: "Profil créé",
  PROFILE_UPDATED: "Profil modifié",
  PROFILE_ARCHIVED: "Profil archivé",
  PROFILE_RESTORED: "Profil restauré",
  PROFILE_ANONYMIZED: "Profil anonymisé",
  PROFILE_DELETED: "Profil supprimé",
  DUPLICATE_ATTEMPT: "Tentative de doublon",
  LOGIN_SUCCESS: "Connexion réussie",
  LOGIN_FAILED: "Échec de connexion",
  LOGOUT: "Déconnexion",
  USER_CREATED: "Utilisateur créé",
  USER_UPDATED: "Utilisateur modifié",
  USER_DEACTIVATED: "Utilisateur désactivé",
  USER_DELETED: "Utilisateur supprimé",
  USER_PASSWORD_CHANGED: "Mot de passe modifié",
  EXPORT_GENERATED: "Export généré",
  REPORT_GENERATED: "Rapport généré",
  SETTINGS_UPDATED: "Paramètres modifiés",
  REFERENTIAL_UPDATED: "Référentiel modifié",

  // FJCS Management
  MEMBER_CREATED: "Membre ajouté",
  MEMBER_UPDATED: "Membre modifié",
  MEMBER_ARCHIVED: "Membre archivé",
  COMMISSION_CREATED: "Commission créée",
  COMMISSION_UPDATED: "Commission modifiée",
  COMMISSION_DELETED: "Commission supprimée",
  MEETING_CREATED: "Réunion créée",
  MEETING_UPDATED: "Réunion modifiée",
  MEETING_CANCELLED: "Réunion annulée",
  MEETING_ARCHIVED: "Réunion archivée",
  ATTENDANCE_RECORDED: "Présence enregistrée",
  ATTENDANCE_CORRECTED: "Présence corrigée",
  ATTENDANCE_TOKEN_ISSUED: "QR de présence généré",
  ATTENDANCE_TOKEN_REVOKED: "QR de présence révoqué",
  MINUTES_CREATED: "Procès-verbal ouvert",
  MINUTES_UPDATED: "Procès-verbal modifié",
  MINUTES_SUBMITTED: "Procès-verbal soumis",
  MINUTES_VALIDATED: "Procès-verbal validé",
  MINUTES_ARCHIVED: "Procès-verbal archivé",
  DECISION_RECORDED: "Décision consignée",
  ACTION_CREATED: "Action créée",
  ACTION_UPDATED: "Action modifiée",
  ACTION_CLOSED: "Action clôturée",
  DOCUMENT_UPLOADED: "Document déposé",
  DOCUMENT_DELETED: "Document supprimé",
  DOCUMENT_DOWNLOADED: "Document téléchargé",
};
